language: c
compiler: gcc
branches:
  only:
    - master
os:
  - linux
install:
  - sudo apt-get install -qq libglib2.0-dev
script:
  - autoreconf -f -i && ./configure && make && sudo make install
after_script:
  - make check
