language: c
compiler: clang
branches:
    except:
        - gh-pages
os:
    - linux
dist: xenial
addons:
    apt:
        update: true
        packages:
            - libglib2.0-dev
            - libxml2-utils
            - autopoint
before_script:
    - autoreconf -f -i -v
script:
    - ./configure && make distcheck
deploy:
    provider: releases
    api_key:
        secure: "BHyNz+01netkQ0knn17Fgj27YUnwtuu/ensNNfMgUaPiobsLHOhXg6W6PCugjCGcBldA5NeLtTf2b1ee64iyGO8Fhh6m4PE0GwkAIjWhbYHHwlvA7G9PWXVhFadXbLezH2iAVzYU8S1pC92qlBwBeBQSnKCSK9wJduaPA35Lz+k="
    file: "rifiuti2-*.tar.xz"
    file_glob: "true"
    skip_cleanup: true
    draft: true
    on:
        tags: true
