language: c
compiler: gcc
branches:
  except:
    - gh-pages
os:
  - linux
install:
  - sudo apt-get install -qq libglib2.0-dev
script:
  - ./autogen.sh && ./configure && make && sudo make install
  - make check TESTSUITEFLAGS='-v'
